// VoiceChatGameMode.cpp

#include "VoiceChatGameMode.h"
#include "VoiceChatCharacter.h"
#include "VoiceChatHUD.h"
#include "UObject/ConstructorHelpers.h"
#include "Blueprint/UserWidget.h"
#include "OpenAIRequester.h"
#include "ChatGPTChatWidget.h"

AVoiceChatGameMode::AVoiceChatGameMode()
{
    UE_LOG(LogTemp, Warning, TEXT("AVoiceChatGameMode Constructor: START")); // <--- ì¶”ê°€

    static ConstructorHelpers::FClassFinder<APawn> PlayerPawnClassFinder(TEXT("/Game/FirstPerson/Blueprints/BP_FirstPersonCharacter"));
    if (PlayerPawnClassFinder.Succeeded())
    {
        DefaultPawnClass = PlayerPawnClassFinder.Class;
        UE_LOG(LogTemp, Warning, TEXT("AVoiceChatGameMode Constructor: DefaultPawnClass FOUND."));
    }
    else
    {
        UE_LOG(LogTemp, Error, TEXT("AVoiceChatGameMode Constructor: FAILED to find DefaultPawnClass. Check path."));
    }

    HUDClass = AVoiceChatHUD::StaticClass();

    // âœ… ìœ„ì ¯ í´ë˜ìŠ¤ ê²½ë¡œëŠ” ë¬´ì¡°ê±´ ìƒì„±ìì—ì„œ!
    static ConstructorHelpers::FClassFinder<UUserWidget> WidgetBPClass(TEXT("/Game/BluePrint/WBP_ChatGPTChat")); // ì‚¬ìš©ìê°€ í™•ì¸í•œ ì •í™•í•œ ê²½ë¡œ
    if (WidgetBPClass.Succeeded())
    {
        WidgetClass = WidgetBPClass.Class;
        UE_LOG(LogTemp, Warning, TEXT("AVoiceChatGameMode Constructor: Successfully found WBP_ChatGPTChat class!"));
    }
    else
    {
        UE_LOG(LogTemp, Error, TEXT("AVoiceChatGameMode Constructor: FAILED to find WBP_ChatGPTChat class at path /Game/BluePrint/WBP_ChatGPTChat. Please double-check the path."));
        WidgetClass = nullptr;
    }
    UE_LOG(LogTemp, Warning, TEXT("AVoiceChatGameMode Constructor: END")); // <--- ì¶”ê°€
}

void AVoiceChatGameMode::BeginPlay()
{
    UE_LOG(LogTemp, Warning, TEXT("AVoiceChatGameMode::BeginPlay() EXECUTED - START")); // <--- ì´ ë¡œê·¸ë¥¼ ì¶”ê°€í•©ë‹ˆë‹¤.
    Super::BeginPlay();

    UE_LOG(LogTemp, Warning, TEXT("AVoiceChatGameMode::BeginPlay() - After Super::BeginPlay()")); // <--- ì´ê²ƒë„ ì¶”ê°€
    // âœ… 1. Requester ìƒì„± ë° ë°”ì¸ë”©
    Requester = NewObject<UOpenAIRequester>(this);
    UE_LOG(LogTemp, Warning, TEXT("AVoiceChatGameMode::BeginPlay() - Requester Object Created")); // <--- ì´ê²ƒë„ ì¶”ê°€
    if (Requester)
    {
        UE_LOG(LogTemp, Warning, TEXT("AVoiceChatGameMode::BeginPlay() - Requester is VALID, binding delegate...")); // <--- ì´ê²ƒë„ ì¶”ê°€
        Requester->OnGPTResponseReceived.AddDynamic(this, &AVoiceChatGameMode::OnGPTResponse);
    }
    else
    {
        UE_LOG(LogTemp, Error, TEXT("AVoiceChatGameMode::BeginPlay() - Requester is NULL!")); // <--- ì´ê²ƒë„ ì¶”ê°€
    }

    // âœ… 2. ìœ„ì ¯ ìƒì„±
    if (WidgetClass)
    {
        ChatWidget = CreateWidget<UChatGPTChatWidget>(GetWorld(), WidgetClass);
        if (ChatWidget)
        {
            ChatWidget->AddToViewport();
        }
    }

    // âœ… 3. API ìš”ì²­
    UE_LOG(LogTemp, Warning, TEXT("AVoiceChatGameMode::BeginPlay() - Attempting to send chat request..."));
    if (Requester)
    {
        Requester->SendChatRequest(TEXT("ì•ˆë…• GPT! Unrealì—ì„œ ë³´ë‚´ëŠ” ë©”ì‹œì§€ì•¼."));
        UE_LOG(LogTemp, Warning, TEXT("AVoiceChatGameMode::BeginPlay() - SendChatRequest CALLED on Requester."));
    }
    else
    {
        UE_LOG(LogTemp, Error, TEXT("AVoiceChatGameMode::BeginPlay() - Cannot SendChatRequest, Requester is NULL."));
    }
    UE_LOG(LogTemp, Warning, TEXT("AVoiceChatGameMode::BeginPlay() EXECUTED - END")); // <--- ì´ê²ƒë„ ì¶”ê°€
}

void AVoiceChatGameMode::OnGPTResponse(const FString& ResponseText)
{
    UE_LOG(LogTemp, Warning, TEXT("ğŸ“¥ GPT ì‘ë‹µ ë„ì°©: %s"), *ResponseText);

    if (ChatWidget)
    {
        ChatWidget->UpdateChat(ResponseText);
    }
}
